language: node_js
node_js:
 - 8.1.4
 - 6.11.1
cache:
  directories:
    - "node_modules"
addons:
  code_climate:
    repo_token: 3b3d167db63a543859a8b0b68698cfdc1dd39e8afe9341f2b66485580e21b8cb
after_success:
  npm install -g codeclimate-test-reporter
  codeclimate-test-reporter < coverage/lcov.info
